Filminurk/Filminurk/Controllers/AccountsController.cs
using Filminurk.Models.Accounts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class AccountsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
      
    }
}

Filminurk/Filminurk/Controllers/ActorsController.cs
using Filminurk.ApplicationServices.Services;
using Filminurk.Core.dto;
using Filminurk.Core.ServiceInterface;
using Filminurk.Data;
using Filminurk.Models.Actors;
using Filminurk.Models.Movies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace Filminurk.Controllers
{
    public class ActorsController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
       private readonly IActorServices _actorService;

        
        public ActorsController
       (
           FilminurkTARpe24Context context,
           IActorServices actorsService
           

       )
        {
            _context = context;
           _actorService = actorsService;


        }
        public IActionResult Index()
        {
            var result = _context.Actors.Select(x => new ActorsIndexViewModel
            {

                ActorID = x.ActorID,
                FirstName = x.FirstName,
                LastName = x.LastName,
                Nickname = x.Nickname,
                Age = x.Age,
                MoviesActedFor = x.MoviesActedFor,
                Addiction = x.Addiction,
                Crimes = x.Crimes,

            });
            return View(result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ActorsIndexViewModel result = new();
            return View("Create", result);
        }





        [HttpPost]
        public async Task<IActionResult> Create(ActorsCreateViewModel vm)
        {

            if (ModelState.IsValid)
            {
                var dto = new ActorDTO()
                {
                    ActorID = vm.ActorID,
                    FirstName = vm.FirstName,
                    LastName = vm.LastName,
                    Nickname = vm.Nickname,
                    Age = vm.Age,
                    MoviesActedFor = vm.MoviesActedFor,
                    Crimes = vm.Crimes,
                    Addiction = vm.Addiction,              
                   



                };
                var result = await _actorService.Create(dto);
                if (result == null)
                {
                    return NotFound();
                }
                if (!ModelState.IsValid)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var actors = await _actorService.Delete(id);

            if (actors == null)
            {
                return NotFound();
            }
          
           

            var vm = new ActorsDeleteView();
            vm.ActorID = actors.ActorID;
            vm.FirstName = actors.FirstName;
            vm.LastName = actors.LastName;
            vm.Nickname = actors.Nickname;
            vm.Age = actors.Age;
            vm.MoviesActedFor = actors.MoviesActedFor;
            vm.Crimes = actors.Crimes;
            vm.Addiction = actors.Addiction;
         

            return View(vm);


        }


    }

}

Filminurk/Filminurk/Controllers/EmailsController.cs
using Filminurk.ApplicationServices.Services;
using Filminurk.Core.dto;
using Filminurk.Core.ServiceInterface;
using Filminurk.Models.Email;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class EmailsController : Controller
    {
        private readonly IEmailsServices _emailServices;
        public EmailsController(IEmailsServices emailServices)
        {
            _emailServices = emailServices;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SendEmail(EmailViewModel vm)
        {
            var dto = new EmailDTO
            {
                SendToThisAddress = vm.SendToThisAddress,
                EmailSubject = vm.EmailSubject,
                EmailContent = vm.EmailContent
            };
            _emailServices.SendEmail(dto);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Register(EmailViewModel vm)
        {

            return View(Index);
        }

        [HttpPost]
        public IActionResult SendRegister(EmailViewModel vm)
        {
            var dto = new EmailDTO
            {
                SendToThisAddress = vm.SendToThisAddress,
                EmailSubject = vm.EmailSubject,
                EmailContent = vm.EmailContent
            };
            _emailServices.SendEmail(dto);
            return RedirectToAction(nameof(Index));


        }
    }
}

Filminurk/Filminurk/Controllers/MoviesController.cs
using System.Data.Entity;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security.Cryptography.Xml;
using AspNetCoreGeneratedDocument;
using Filminurk.ApplicationServices.Services;
using Filminurk.Core.Domain;
using Filminurk.Core.dto;
using Filminurk.Core.Dto;
using Filminurk.Core.ServiceInterface;
using Filminurk.Data;
using Filminurk.Models.Movies;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class MoviesController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        private readonly IMoviesServices _movieservices;
        private readonly IFilesServices _filesServices; //Piltide lisamiseks vajalik fileservices injection

        public MoviesController
        (
            FilminurkTARpe24Context context,
            IMoviesServices movieServices     ,
            IFilesServices filesServices

        )
        {
            _context = context;
            _movieservices = movieServices;
            _filesServices = filesServices;

        }
        public IActionResult Index()
        {
            var result = _context.Movies.Select(x => new MoviesIndexViewModel
            {

                ID = x.ID,
                Title = x.Title,
                FirstPublished = x.FirstPublished,
                CurrentRating = x.CurrentRating,
                Genre = x.Genre,
                AgeRating = x.AgeRating,

            });
            return View(result);
        }
        [HttpGet]
        public async Task<IActionResult> Update(Guid ID)
        {
            var movie = await _movieservices.DetailsAsync(ID);

            if (movie == null)
            {
                return NotFound();
            }

            var images = await _context.FilesToApi
                .Where(x => x.MovieID == ID)
                .Select(y => new ImageViewModel
                {
                    FilePath = y.ExistingFilePath,
                    ImageID = ID

                }).ToArrayAsync();

            var vm = new MoviesCreateUpdateViewModel();
            {
                vm.ID = movie.ID;
                vm.Title = movie.Title;
                vm.Description = movie.Description;
                vm.FirstPublished = movie.FirstPublished;
                vm.Director = movie.Director;
                vm.Actors = movie.Actors;
                vm.CurrentRating = movie.CurrentRating;
                vm.AgeRating = movie.AgeRating;
                vm.Genre = movie.Genre;
                vm.IMDBrating = movie.IMDBrating;
                vm.EntryCreatedAt = movie.EntryCreatedAt;
                vm.EntryModifedAt = movie.EntryModifedAt;
                vm.Images.AddRange(images);


                return View("CreateUpdate", vm);

            }
        }
        
        
        
        


        [HttpPost]

        public async Task<IActionResult> UpdateAsync(MoviesCreateUpdateViewModel vm)
        {

            var dto = new MoviesDTO()
            {
                ID = vm.ID,
                Title = vm.Title,
                Description = vm.Description,
                FirstPublished = vm.FirstPublished,
                Director = vm.Director,
                Actors = vm.Actors,
                CurrentRating = vm.CurrentRating,
                AgeRating = vm.AgeRating,
                Genre = vm.Genre,
                IMDBrating = vm.IMDBrating,
                EntryCreatedAt = vm.EntryCreatedAt,
                EntryModifedAt = vm.EntryModifedAt,
                Files = vm.Files,
                FileToApiDTOs = vm.Images
                .Select(x => new FileToApiDTO
                {
                    ImageID = x.ImageID,
                    MovieID = x.MovieID,
                    FilePath = x.FilePath,
                }).ToArray()             
            };
            var result = await _movieservices.Update(dto);

            if (result == null)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }


           [HttpGet]
            public IActionResult Create()
            {
                MoviesCreateUpdateViewModel result = new();
                return View("CreateUpdate", result);
            }

        



        [HttpPost]
        public async Task<IActionResult> Create(MoviesCreateUpdateViewModel vm)
        {

            if (ModelState.IsValid)
            {
                var dto = new MoviesDTO()
                {
                    ID = vm.ID,
                    Title = vm.Title,
                    Description = vm.Description,
                    FirstPublished = vm.FirstPublished,
                    Director = vm.Director,
                    Actors = vm.Actors,
                    CurrentRating = vm.CurrentRating,
                    AgeRating = vm.AgeRating,
                    Genre = vm.Genre,
                    IMDBrating = vm.IMDBrating,
                    EntryCreatedAt = vm.EntryCreatedAt,
                    EntryModifiedAT = vm.EntryModifedAt,
                    Files = vm.Files,
                    FileToApiDTOs = vm.Images
                    .Select(x => new FileToApiDTO
                    {
                        ImageID = x.ImageID,
                        FilePath = x.FilePath,
                        MovieID = x.MovieID,
                        IsPoster = x.IsPoster,
                    }).ToArray()

                };
                var result = await _movieservices.Create(dto);
                if (result == null)
                {
                    return NotFound();
                }
                if (!ModelState.IsValid)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

            [HttpGet]
            public async Task<IActionResult> Delete(Guid id)
            {
                var movie = await _movieservices.DetailsAsync(id);

                if (movie == null)
                {
                    return NotFound();
                }
                var images = await _context.FilesToApi
                .Where(x => x.MovieID == id)
                .Select(y => new ImageViewModel
                {
                FilePath = y.ExistingFilePath,
                ImageID = y.ImageID,

                }).ToArrayAsync();

                var vm = new MoviesDeleteViewModel();
                vm.ID = movie.ID;
                vm.Title = movie.Title;
                vm.Description = movie.Description;
                vm.FirstPublished = movie.FirstPublished;
                vm.Director = movie.Director;
                vm.Actors = movie.Actors;
                vm.CurrentRating = movie.CurrentRating;
                vm.AgeRating = movie.AgeRating;
                vm.Genre = movie.Genre;
                vm.IMDBrating = movie.IMDBrating;
                vm.EntryCreatedAt = movie.EntryCreatedAt;
                vm.EntryModifedAt = movie.EntryModifedAt;
                vm.Images.AddRange(images);

                return View(vm);
                
               
            }
        [HttpGet]

        public async Task <IActionResult> Details(Guid id)
        {
            var movie = await _movieservices.DetailsAsync(id);

                if (movie == null)
            {
                return NotFound();
            }

                ImageViewModel[] images = await FileFromDatabase(id);

                var vm = new MoviesDetailsViewModel();

                vm.ID = movie.ID;
                vm.Title = movie.Title;
                vm.Description = movie.Description;
                vm.FirstPublished = movie.FirstPublished;
                vm.Director = movie.Director;
                vm.Actors = movie.Actors;
                vm.CurrentRating = movie.CurrentRating;
                vm.AgeRating = movie.AgeRating;
                vm.Genre = movie.Genre;
                vm.IMDBrating = movie.IMDBrating;
                vm.EntryCreatedAt = movie.EntryCreatedAt;
                vm.EntryModifedAt = movie.EntryModifedAt;
                vm.Images.AddRange(images);

                return View("CreateUpdate",vm);

            }

        [HttpPost]
        public async Task<IActionResult> Update(MoviesCreateUpdateViewModel vm)
        {
            var dto = new MoviesDTO()
            {
             ID = vm.ID,
             Title = vm.Title,
             Description = vm.Description,
             FirstPublished = vm.FirstPublished,
             Director = vm.Director,
             Actors = vm.Actors,
             CurrentRating = vm.CurrentRating,
             AgeRating = vm.AgeRating,
             Genre = vm.Genre,
             IMDBrating = vm.IMDBrating,
             EntryCreatedAt = vm.EntryCreatedAt,
             EntryModifedAt = vm.EntryModifedAt,
             Files = vm.Files,
             FileToApiDTOs = vm.Images


                
                .Select(x => new FileToApiDTO
                {
                    ImageID = x.ImageID,
                    MovieID = x.MovieID,
                    FilePath = x.FilePath
                }).ToArray()
            };
            var result = await _movieservices.Update(dto);

            if (result == null)
            {
                return NotFound();
            }
            return RedirectToAction(nameof(Index));
        }














        [HttpPost]
            public async Task<IActionResult> DeleteConfirmation(Guid id)
            {
                var movie = await _movieservices.Delete(id);
                if (movie == null)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
        private async Task<ImageViewModel[]> FileFromDatabase(Guid id)
        {
            return await _context.FilesToApi
                .Where(x => x.MovieID == id)

Filminurk/Filminurk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Filminurk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Filminurk.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Filminurk</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Avaleht</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Filmid</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="Index">Actors</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserComments" asp-action="Index">Comment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FavouriteLists" asp-action="Index">My favourite list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emails" asp-action="Index">Saada kiri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Index">Konto</a>
                        </li>
                    </ul>
                    <ul>
                        @if(signInManager.IsSigned(user))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="">Minu lemmikute nimekirjad</a>

                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Accounts" asp-action="LogOut">
                                    <button type="submit" class="nav-link btn-btn-link" style="width:auto;padding:0.8rem
"
                                </form>

                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Filminurk - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)



</body>
</html>