Filminurk/Filminurk/Models/FavouriteList/FavouriteCreateViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.FavouriteList
{
    public class FavouriteCreateViewModel
    {
        public Guid? FavouriteListID { get; set; }

        public string ListBelongsToUser { get; set; }

        public bool IsMovieOrActor { get; set; }

        public string ListName { get; set; }

        public string ListDescription { get; set; }

        public bool IsPrivate { get; set; }

        public List<Movie>? ListOfMovies { get; set; }

        public DateTime? ListCreatedAt { get; set; }
    

        public DateTime? ListModifiedAt { get; set; }

        public DateTime? ListDeletedAt { get; set; }
        public bool IsReported { get; set; }
        // imagemodel for index
        public List<FavouriteListIndexImageViewModel> Image { get; set; } = new List<FavouriteListIndexImageViewModel>();
    }
}

Filminurk/Filminurk/Models/FavouriteList/FavouriteListAdminCreateEditViewModel.cs
using Filminurk.Core.Domain;
using System.ComponentModel.DataAnnotations;

namespace Filminurk.Models.FavouriteList
{
    public class FavouriteListAdminCreateEditViewModel
    {
        
       
            public Guid FavouriteListID { get; set; }

            public string ListBelongsToUser { get; set; }

            public bool IsMovieOrActor { get; set; }

            public string ListName { get; set; }
            public string? ListDescription { get; set; }
            public bool IsPrivate { get; set; }

            public List<Movie>? ListOfMovies { get; set; }

            public DateTime? ListCreatedAt { get; set; }

            public DateTime? ListModified { get; set; }

            public DateTime ListDeletedAt { get; set; }

            public bool IsReported { get; set; }


        public List<FavouriteListIndexImageViewModel> Image { get; set; } = new List<FavouriteListIndexImageViewModel>();
        }
    }

Filminurk/Filminurk/Models/FavouriteList/FavouriteListDetailsViewModel.cs
using Filminurk.Core.Domain;

namespace Filminurk.Models.FavouriteList
{
    public class FavouriteListDetailsViewModel
    {
        public Guid? FavouriteListID { get; set; }

        public string ListBelongsToUser { get; set; }

        public bool IsMovieOrActor { get; set; }

        public string ListName { get; set; }

        public string ListDescription { get; set; }

        public bool IsPrivate { get; set; }

        public List<Movie>? ListOfMovies { get; set; }

        public DateTime? ListCreatedAt { get; set; }


        public DateTime? ListModifiedAt { get; set; }

        public DateTime ListDeletedAt { get; set; }
        public bool? IsReported { get; set; }
        // imagemodel for index
        //public FavouriteListIndexImageViewModel Image { get; set; } = new FavouriteListIndexImageViewModel();
    }
}

Filminurk/Filminurk/Models/FavouriteList/FavouriteListIndexImageViewModel.cs
namespace Filminurk.Models.FavouriteList
{
    public class FavouriteListIndexImageViewModel
    {
        public Guid? ImageID { get; set; }
        public string ImageTitle { get; set; }
        public byte[] ImageData { get; set; }
        public string Image {  get; set; }
        public Guid? ListID { get; set; }
    }
}

Filminurk/Filminurk/Controllers/FavouriteListController.cs
using System.ComponentModel;
using AspNetCoreGeneratedDocument;
using Filminurk.Core.Domain;
using Filminurk.Core.dto;
using Filminurk.Core.ServiceInterface;
using Filminurk.Data;
using Filminurk.Models.FavouriteList;
using Filminurk.Models.Movies;
using Microsoft.AspNetCore.Mvc;

namespace Filminurk.Controllers
{
    public class FavouriteListController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        private readonly IFavouriteListsServices _favouriteListsServices;
        public FavouriteListController( FilminurkTARpe24Context context, IFavouriteListsServices favouriteListsServices )
        {
            _context = context;
            _favouriteListsServices = favouriteListsServices;
        }
        public IActionResult Index()
        {
            var resultingLists = _context.FavouriteLists.OrderByDescending(y => y.ListCreatedAt)
            .Select(x => new FavouriteListIndexViewModel
            {
                FavouriteListID = x.FavouriteListID,
                ListBelongsToUser = x.ListBelongsToUser,
                IsMovieOrActor = x.IsMovieOrActor,
                ListName = x.ListName,
                ListDescription = x.ListDescription,
                ListCreatedAt = x.ListCreatedAt,
                Image =(List<FavouriteListIndexImageViewModel>)_context.FilesToDatabase.Where(ml => ml.ListID == x.FavouriteListID)
                .Select(li => new FavouriteListIndexImageViewModel
                {
                    ListID = li.ListID,
                    ImageID = li.ImageID,
                    ImageData = li.ImageData,
                    ImageTitle = li.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(li.ImageData)),
                })

            });
            return View();
        }
        /* create get, create post */

        [HttpGet]
        
        public IActionResult Create()
        {
            var movies = _context.Movies.OrderBy(m => m.Title).Select(mo => new MoviesIndexViewModel
            {
                ID = mo.ID,
                Title = mo.Title,
                FirstPublished = mo.FirstPublished,
                Genre = mo.Genre,


            }).ToList();
            ViewData["allmovies"] = movies;
            ViewData["UserHasSelected"] = new List<string>();
            //this for normal user
            FavouriteCreateViewModel vm = new();
            return View("Create", vm);
        }


        [HttpPost]
        public async Task<IActionResult> Create(FavouriteCreateViewModel vm, List<string> userhasSelected,List<MoviesIndexViewModel> movies)
        {

            List<Guid> tempParse = new();
            foreach (var stringID in userhasSelected)
            {
                tempParse.Add(Guid.Parse(stringID));

            }

            var newListDto = new FavouriteListDTO() { };
            newListDto.ListName = vm.ListName;
            newListDto.ListDescription = vm.ListDescription;
            newListDto.IsMovieOrActor = vm.IsMovieOrActor;
            newListDto.IsPrivate = vm.IsPrivate;
            newListDto.ListCreatedAt = DateTime.UtcNow;
            newListDto.ListBelongsToUser = "00000000-0000-0000-000000000001";
            newListDto.ListModifiedAt = DateTime.UtcNow;    
            newListDto.ListDeletedAt = vm.ListDeletedAt;

            List<Guid> convertedIDs= new List<Guid>();
            if (newListDto.ListOfMovies !=null)         
            {
                convertedIDs = MovieToid(newListDto.ListOfMovies);


             }
            var newlist = await _favouriteListsServices.Create(newListDto, convertedIDs);
            if (newlist != null)
            {
                return BadRequest();
            }
            return RedirectToAction("Index", vm);


        
    }

        private List<Guid> MovieToid(List<Movie> listOfMovies)
        {
            var result = new List<Guid>();
            foreach (var movie in listOfMovies)
            {
                result.Add(movie.ID);
            }
            return result;
        }
        }
    }

Filminurk/Filminurk/Controllers/FavouriteListsController.cs
using System.ComponentModel;
using System.Drawing;
using System.Linq;
using AspNetCoreGeneratedDocument;
using Filminurk.Core.Domain;
using Filminurk.Core.dto;
using Filminurk.Core.ServiceInterface;
using Filminurk.Data;
using Filminurk.Models.FavouriteList;
using Filminurk.Models.Movies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;

namespace Filminurk.Controllers
{
    public class FavouriteListsController : Controller
    {
        private readonly FilminurkTARpe24Context _context;
        private readonly IFavouriteListsServices _favouriteListsServices;
        public FavouriteListsController(FilminurkTARpe24Context context, IFavouriteListsServices favouriteListsServices)
        {
            _context = context;
            _favouriteListsServices = favouriteListsServices;
        }
        public IActionResult Index()
        {
            var resultingLists = _context.FavouriteLists.OrderByDescending(y => y.ListCreatedAt)
            .Select(x => new FavouriteListIndexViewModel
            {
                FavouriteListID = x.FavouriteListID,
                ListBelongsToUser = x.ListBelongsToUser,
                IsMovieOrActor = x.IsMovieOrActor,
                ListName = x.ListName,
                ListDescription = x.ListDescription,
                ListCreatedAt = x.ListCreatedAt,
                ListDeletedAt = (DateTime)x.ListDeletedAt,
                Image = (List<FavouriteListIndexImageViewModel>)_context.FilesToDatabase.Where(ml => ml.ListID == x.FavouriteListID)
                .Select(li => new FavouriteListIndexImageViewModel
                {
                    ListID = li.ListID,
                    ImageID = li.ImageID,
                    ImageData = li.ImageData,
                    ImageTitle = li.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(li.ImageData)),
                })

            });
            return View(resultingLists);
        }
        /* create get, create post */

        [HttpGet]

        public IActionResult Create()
        
        
        
        {
            var movies = _context.Movies.OrderBy(m => m.Title).Select(mo => new MoviesIndexViewModel
            {
                ID = mo.ID,
                Title = mo.Title,
                FirstPublished = mo.FirstPublished,
                Genre = mo.Genre,


            }).ToList();
            ViewData["allmovies"] = movies;
            ViewData["UserHasSelected"] = new List<string>();
            //this for normal user
            FavouriteCreateViewModel vm = new();
            return View("Create", vm);
        }


        [HttpPost]
        public async Task<IActionResult> Create(FavouriteCreateViewModel vm, List<string> userhasSelected, List<MoviesIndexViewModel> movies)
        {

            List<Guid> tempParse = new();
            //tekkib ajutine guid list movieid-de hoidmiseks
            foreach (var stringID in userhasSelected)
            {
                //lisame iga stringi kohta järjendis userhasselected teisendatud guidi
                tempParse.Add(Guid.Parse(stringID));

            }

            var newListDto = new FavouriteListDTO() { };
            newListDto.ListName = vm.ListName;
            newListDto.ListDescription = vm.ListDescription;
            newListDto.IsMovieOrActor = vm.IsMovieOrActor;
            newListDto.IsPrivate = vm.IsPrivate;
            newListDto.ListCreatedAt = DateTime.UtcNow;
            newListDto.ListBelongsToUser = Guid.NewGuid().ToString();
            newListDto.ListModifiedAt = DateTime.UtcNow;
            newListDto.ListDeletedAt = null;


            //lisa filmid nimekirja,olemasolevate id-de põhiliselt 
            var listofmoviestoadd = new List<Movie>();
            foreach (var movieId in tempParse)
            {
                Movie thismovie = (Movie)_context.Movies.Where(tm => tm.ID == movieId).ToList().First();
                
            }
            newListDto.ListOfMovies = vm.ListOfMovies;
            //List<Guid> convertedIDs= new List<Guid>();
            //if (newListDto.ListOfMovies !=null)         
            //{
            //    convertedIDs = MovieToid(newListDto.ListOfMovies);
            // }
            var newlist = await _favouriteListsServices.Create(newListDto /*, convertedIDs*/);
            if (newlist == null)
            {
                return BadRequest();
            }
            return RedirectToAction("Index", vm);

            }
            [HttpGet]
            public async Task<IActionResult> UserDetails(Guid id, Guid thisuserid)
            {
                if (id == null || thisuserid == null)
                {
                    return BadRequest();
                    //T0D0 return corresponding errorviews. id not found for list, and user login error for userid
                }
                //var images = _context.FilesToDatabase
                //    .Where(i => i.ListID == id)
                //    .Select(si => new FavouriteListIndexImageViewModel
                //    {
                //        ImageID = si.ImageID,
                //        ListID = si.ListID,
                //        ImageData = si.ImageData,
                //        ImageTitle = si.ImageTitle,
                //        Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(si.ImageData))
                //    }).ToList().First();

                var thislist = _context.FavouriteLists.Where(tl => tl.FavouriteListID == id && tl.ListBelongsToUser == thisuserid.ToString())
                .Select(stl => new FavouriteListDetailsViewModel
                {
                    FavouriteListID = stl.FavouriteListID,
                    ListBelongsToUser = stl.ListBelongsToUser,
                    IsMovieOrActor = stl.IsMovieOrActor,
                    ListName = stl.ListName,
                    ListDescription = stl.ListDescription,
                    IsPrivate = stl.IsPrivate,
                    ListOfMovies = stl.ListOfMovies,
                    IsReported = stl.IsReported
                    //    Image = _context.FilesToDatabase
                    //    .Where(i => i.ListID == stl.FavouriteListID)
                    //    .Select(si => new FavouriteListIndexImageViewModel
                    //    {
                    //        ImageID = si.ImageID,
                    //        ListID = si.ListID,
                    //        ImageData = si.ImageData,
                    //        ImageTitle = si.ImageTitle,

                    //}).ToList();
                }).First();
                //images = images;
                //if (!ModelState.IsValid)
                //{
                //    //     return NotFound();
                //}
                //Add viewdata attribute here later, to discern between user and admin
                if (thislist == null)
                {
                    return NotFound();
                }
                return View("Details", thislist);
            }
        [HttpPost]
        public  async Task<IActionResult> UserTogglePrivacy(Guid id)
        {
            FavouriteList thisList = await _favouriteListsServices.DetailsAsync(id);

            FavouriteListDTO updatedList = new FavouriteListDTO();
            updatedList.FavouriteListID = thisList.FavouriteListID;
            updatedList.ListBelongsToUser = thisList.ListBelongsToUser;
            updatedList.ListName = thisList.ListName;
            updatedList.ListDescription = thisList.ListDescription;
            updatedList.IsPrivate = !thisList.IsPrivate;
            updatedList.ListOfMovies = thisList.ListOfMovies;
            updatedList.IsReported = thisList.IsReported;
            updatedList.IsMovieOrActor = thisList.IsMovieOrActor;
            updatedList.ListCreatedAt = (DateTime)thisList.ListCreatedAt;
            updatedList.ListModifiedAt = DateTime.Now;
            updatedList.ListDeletedAt = thisList.ListDeletedAt;
            



            var result = await _favouriteListsServices.Update(updatedList,"Private");
            if (result == null)
            {
                return NotFound();
            }


            //if (result.IsPrivate != result.IsPrivate)
            //{
            //    return BadRequest();
            //}



            return RedirectToAction(nameof(Index));
        
           
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {


            var deletedList = await _favouriteListsServices.DetailsAsync(id);
            deletedList.ListDeletedAt = DateTime.Now;

            var dto = new FavouriteListDTO();
            
            dto.FavouriteListID = deletedList.FavouriteListID;
            dto.FavouriteListID = deletedList.FavouriteListID;
            dto.ListBelongsToUser = deletedList.ListBelongsToUser;
            dto.IsMovieOrActor = deletedList.IsMovieOrActor;
            dto.ListName = deletedList.ListName;
            dto.ListDescription = deletedList.ListDescription;
            dto.IsPrivate = deletedList.IsPrivate;
            dto.ListOfMovies = deletedList.ListOfMovies;
            dto.ListCreatedAt = (DateTime)deletedList.ListCreatedAt;
            dto.ListDeletedAt = DateTime.Now;
            dto.ListModifiedAt = DateTime.Now;
           

            var result = await _favouriteListsServices.Update(dto,"Delete");
            if (result == null)
            {
                NotFound();
            }

            
            return RedirectToAction("Index");
        }


        private List<Guid> MovieToid(List<Movie> listOfMovies)
        {
            var result = new List<Guid>();
            foreach (var movie in listOfMovies)
            {
                result.Add(movie.ID);
            }
            return result;
        }
        }
    }

Filminurk/Filminurk/Views/FavouriteLists/Create.cshtml
@using Filminurk.Core.Domain
@model Filminurk.Models.FavouriteList.FavouriteCreateViewModel
@*check for editing or creating*@
@{
	var allMoviesTickBoxes = ViewData["allmovies"] as List<Filminurk.Models.Movies.MoviesIndexViewModel>;
	List<string> userHasSelected = ViewBag.userHasSelected;
	List<string> previouslySelected = userHasSelected;

}
<h1>Tee uus nimekiri</h1>
<div>
	<form method="post" enctype="multipart/form-data">
		<input asp-for="FavouriteListID" type="hidden" />
		<input asp-for="ListCreatedAt" type="hidden" />
		<input asp-for="ListModifiedAt" type="hidden" />
		<input asp-for="ListDeletedAt" type="hidden" />
		<input asp-for="IsReported" type="hidden"/>
	

	<div class="form-group-row">
		<label asp-for="ListName" class="col-sm-2 col-form-label"></label>
		<div class="col-sm-10">
			<input asp-for="ListName" class="form-control" />
		</div>
	</div>

	<div class="form-group-row">
		<label asp-for="ListDescription" class="col-sm-2 col-form-label"></label>
		<div class="col-sm-10">
			<input asp-for="ListDescription" class="form-control" />
		</div>
	</div>

	<div class="form-group-row">
		<label asp-for="IsPrivate" class="col-sm-2 col-form-label"></label>
		<div class="col-sm-10">
			<input type="checkbox" asp-for="IsPrivate"  class="form-control"/>
		</div>
	</div>

	@if (allMoviesTickBoxes == null)
		{

		<tr>Filme andmebaasis ei ole</tr>

	}
	else
	
	{
	foreach(var movie in allMoviesTickBoxes)
	{
	<tr>
		<td>movie.Title</td>
		<td>movie.FirstPublished</td>
		<td>movie.MovieGenre</td>
		<td>
					
			@if(movie.ID.HasValue)
			{
				
			
						<input 
						type="checkbox"
						name="userHasSelected"
						value="@movie.ID"
						id="checkbox-@movie.ID" 
						@if (userHasSelected.Contains(movie.ID.ToString()))
						{
					     @:checked
				        }
					/>
			} 
			else{ 
				
					<input type="checkbox" name="userHasSelected" value="@movie.ID" id="checkbox-@movie.ID" />
				
	         }


				</td>
				<br />
			</tr>
		}
	}
	<input asp-action="Create" asp-controller="FavouriteLists" type="submit" method="post"class="btn btn-primary" value="Tee nimekiri"/>
	</form>

</div>

Filminurk/Filminurk/Views/FavouriteLists/Details.cshtml
@model Filminurk.Models.FavouriteList.FavouriteListDetailsViewModel
@{
	int rowNumber = 1;
}
<div>
	@if (Model.IsReported == true)
	{
		@:Sinu nimekiri rikub kogukonna reegleid<br/>
		@:oleme seadnud nimekirja privaatseks kuni admin selle üle vaatab <br/>
	}
	<table>
		<tr><h1>@Model.ListName</h1></tr>
		@* <tr><partial name="_ImageIndex" model="@Model.Image"></partial></tr> *@
		<tr>@Model.IsPrivate.ToString() </tr>
	</table>
</div>


<div>
	
	<form method="post"> 

	<table class="table">
			@foreach (var movie in Model.ListOfMovies)
			{
		<tr>
			<table class="table" style="border:thick;">
				<tr>
					<td colspan="2">@movie.Title</td>
				</tr>
				<tr>
						<td>(IMAGE HERE)</td>
					<td>
						<table>
							<tr>@movie.Description</tr>
								<tr>@movie.Director</tr>
								<tr>@movie.CurrentRating</tr>
								<tr>@movie.Genre</tr>
						</table>
					</td>
				</tr>
			</table>
		</tr>
			}

			</table>
			
			<div>
				
		<input asp-action="UserDelete" asp-controller="FavouriteLists" asp-route-id="@Model.FavouriteListID" type="submit" class="btn btn-danger"value="Kustuta Nimekiri" />

		@* <a asp-action="UserTogglePrivacy" asp-controller="FavouriteLists" asp-route-id="@Model.FavouriteListID" formethod="get" class="btn btn-warning"  asp-route-id="@Model.FavouriteListID" asp-route-thisuserid="@Model.ListBelongsToUser">Click</a> *@


			<input asp-action="UserTogglePrivacy" asp-controller="FavouriteLists" asp-route-id="@Model.FavouriteListID" type="submit" class="btn btn-warning" value="Muuda Nimekiri Privaatseks" />

		<input asp-action="UserEditList" asp-controller="FavouriteLists" asp-route-id="@Model.FavouriteListID" type="submit" class="btn btn-success" value="Muuda Nimekirja Sisu Ja Andmeid" />
		<a asp-action="Index" asp-controller="FavouriteLists" class="btn btn-light">Tagasi</a>
		</div>
	</form>
</div>

Filminurk/Filminurk/Views/FavouriteLists/Index.cshtml
@model IEnumerable<Filminurk.Models.FavouriteList.FavouriteListIndexViewModel>

@{
	int rowNumber = 1;
	int CurrentRow = 1;
	int CurrentTitle = 1;
	int titlesInRow = 1;

}
<div>
	<a asp-action="Create" asp-controller="FavouriteLists" class="btn btn-primary">Tee uus lemmikute nimekiri</a>
	<a asp-action="Index" asp-controller="Home" class="btn btn-primary">Pealeht</a>
</div>
<div>
	<div @*no class currently, no design specified*@>
		<form method="post">
			<table class="table">
				<thead>
					@if (!Model.Any())
					{
						<tr>
							<th scope="col" colspan="2">
								<span>Kahjuks ei leidnud ühtegi lemmikute nimekirja</span>
							</th>
						</tr>
					}
					else
					{
						<tr>
							<th scope="col" colspan="2">
								<span>Sinu nimekirjad</span>
							</th>
						</tr>
					}
				</thead>
				<tbody>
					@if (!Model.Any())
					{
						<table>
							<tr>
								<td colspan="2">Sorry,no list</td>
							</tr>
							<tr>
								<td><img  width="128" src="~/lib/defaultassets/image/noposter.png"/></td>
							</tr>
						</table>
					}
					else
						@foreach(var list in Model)
						{
							if (list.ListDeletedAt == null )
								{
									
								
							<table>
								<tr>
									<td colspan="2">
										<a asp-action="UserDetails" asp-controller="FavouriteLists" asp-route-id="@list.FavouriteListID" asp-route-thisuserid=@list.ListBelongsToUser>@list.ListName </a>
									</td>
								</tr>
								<tr>
									<td>
										@list.ListDeletedAt.ToString()
										@foreach (var image in list.Image)
										{
											<partial name="_ImageIndex" model="image"/>
										}
									  <td><img width="128" src="~/lib/defaultassets/image/noposter.png" /></td>
									</td>
									<td>@list.ListDescription</td>
								</tr>
								</table>
							}
							rowNumber++;

						}
				</tbody>
			</table>
		</form>




	</div>


</div>

Filminurk/Filminurk/Views/FavouriteLists/UserTogglePrivacy.cshtml
@model Filminurk.Models.FavouriteList.FavouriteListDetailsViewModel
@{
	int rowNumber = 1;
}
<div>
	<h1>USERTOGGLEPRIVACY</h1>
	@if (Model.IsReported == true)
	{
		@:Sinu nimekiri rikub kogukonna reegleid<br />
		@:oleme seadnud nimekirja privaatseks kuni admin selle üle vaatab <br />
	}
	<table>
		<tr><h1>@Model.ListName</h1></tr>
		@* <tr><partial name="_ImageIndex" model="@Model.Image"></partial></tr> *@
		<tr>@Model.IsPrivate</tr>
	</table>
</div>
<div>
	<form method="post">

		<table class="table">
			@foreach (var movie in Model.ListOfMovies)
			{
				<tr>
					<table class="table" style="border:thick;">
						<tr>
							<td colspan="2">@movie.Title</td>
						</tr>
						<tr>
							<td>(IMAGE HERE)</td>
							<td>
								<table>
									<tr>@movie.Description</tr>
									<tr>@movie.Director</tr>
									<tr>@movie.CurrentRating</tr>
									<tr>@movie.Genre</tr>
								</table>
							</td>
						</tr>
					</table>
				</tr>

			}
		</table>
		<div>
			

			<input asp-action="UserTogglePrivacy" asp-controller="FavouriteLists" asp-route-id="@Model.FavouriteListID" type="submit" class="btn btn-warning" value="Muuda Nimekiri Privaatseks" />

			
			<a asp-action="Index" asp-controller="FavouriteLists" class="btn btn-light">Tagasi</a>
		</div>
	</form>
</div>

Filminurk/Filminurk/Views/FavouriteLists/_ImageIndex.cshtml
@model Filminurk.Models.FavouriteList.FavouriteListIndexImageViewModel
<div>
	@if (!Model.Image.Any() ||Model == null)
	{
		<p> Pilte pole</p>
	}	
</div>
@if(Model.ImageTitle == "Poster")
{
	<img class="card-image-top" src="@Model.Image" asp-append-version="true"/>
}
else
{
	<img width="128" src="~/lib/defaultassets/image/noposter.png" />
}